name: Compile Mod Templates
run-name: Template files are being compiled
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
jobs:
  Compile-Templates:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[Automatic]') && !startsWith(github.event.head_commit.message, '[Nobuild]') }}
    steps:
    - uses: actions/checkout@v3
    - uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Tokyo"
        timezoneMacos: "Asia/Tokyo"
        timezoneWindows: "Japan Standard Time"
    - name: Cleanup old Arena files
      run: rm -rfv releases/*
    - uses: actions/setup-node@v3
    - name: Compile Arena files
      run: npm run compile
    - name: Deploy Arena files
      run: |
        git config user.name "Bhpsngum"
        git config user.email "bhpsngumproductions@gmail.com"
        git add .
        git commit -m "[Automatic] Build arena files ${GITHUB_SHA}"
        git push -u https://bhpsngum:${secrets.GITHUB_TOKEN}@github.com/bhpsngum/Arena-mod-remake.git HEAD